name: testing.yml
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install -g turbo orval jest prettier
          pnpm install

#      - name: Install dependencies
#        uses: pnpm/action-setup@v2
#        with:
#          version: '10.0.0'
#        run: |
#          pnpm install -g turbo orval jest prettier
#          pnpm install

      - name: Run tests
        run: |
          pnpm run test

      - name: Build package
        run: |
          pnpm run build